name: Deploy PR Preview
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  deploy:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy Main to Root
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
          target-folder: .
          clean: false

      - name: Deploy PR Preview
        if: github.event_name == 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . 
          branch: gh-pages
          target-folder: previews/pr-${{ github.event.number }}
          clean: false

  cleanup:
    # This runs only when the PR is merged or closed
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create Empty Directory
        run: mkdir empty_dir

      - name: Delete Preview Folder
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: empty_dir       # Deploying an empty folder...
          target-folder: previews/pr-${{ github.event.number }} # ...to the PR path
          branch: gh-pages
          clean: true             # ...wipes that path clean